# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: IDOBAO Help
email: info@idobao.net
#description: >- # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://idobao.github.io" # the base hostname & protocol for your site, e.g. http://example.com
owner: IDOBAO
copyright: 2022

# github_raw_path: https://raw.githubusercontent.com/Idobao/idobao.github.io/master
github_raw_path: https://cdn.jsdelivr.net/gh/Idobao/idobao.github.io
github_release_path: https://cdn.jsdelivr.net/gh/Idobao/idobao.github.io/release/firmware
github_qmk_path: https://github.com/qmk/qmk_firmware/tree/master/keyboards/idobao
github_via_path: https://github.com/the-via/keyboards/blob/master/v3

# Build settings
markdown: kramdown
theme: minima
#plugins:
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - .sass-cache
  - .vscode
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - bin/
  - release/
  - "*.hex"
  - "*.bin"
  - "*.json"
  - "__*"
  

# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
